# Site settings
title: San's world
email: hueidou163@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://san.sanrabbit.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  hueidou
disqus: hueidou

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html